### ISSUE TITLE
Exception java.lang.IllegalStateException: Already resumed, but proposed with update false

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/cert4android#26] opened 2023-09-11 09:50 UTC
I've copied this from the Google Play Console. Not occurring often but we should fix it ;-)

```
Exception java.lang.IllegalStateException: Already resumed, but proposed with update false
  at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError (CancellableContinuationImpl.kt:559)
  at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl (CancellableContinuationImpl.kt:524)
  at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default (CancellableContinuationImpl.kt:497)
  at kotlinx.coroutines.CancellableContinuationImpl.resumeWith (CancellableContinuationImpl.kt:368)
  at at.bitfire.cert4android.UserDecisionRegistry.onUserDecision (UserDecisionRegistry.kt:113)
  at at.bitfire.cert4android.TrustCertificateActivity$Model.registerDecision (TrustCertificateActivity.kt:312)
  at at.bitfire.cert4android.TrustCertificateActivity$onCreate$2.handleOnBackPressed (TrustCertificateActivity.kt:77)
  at androidx.activity.OnBackPressedDispatcher.onBackPressed (OnBackPressedDispatcher.kt:213)
  at androidx.activity.ComponentActivity.onBackPressed (ComponentActivity.java:694)
  at android.app.Activity.onKeyUp (Activity.java:3940)
  at android.view.KeyEvent.dispatch (KeyEvent.java:3143)
  at android.app.Activity.dispatchKeyEvent (Activity.java:4286)
  at androidx.core.app.ComponentActivity.superDispatchKeyEvent (ComponentActivity.java:126)
  at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent (KeyEventDispatcher.java:86)
  at androidx.core.app.ComponentActivity.dispatchKeyEvent (ComponentActivity.java:144)
  at com.android.internal.policy.DecorView.dispatchKeyEvent (DecorView.java:415)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent (ViewRootImpl.java:6664)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:6530)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:5990)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:6047)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:6013)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:6178)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:6021)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:6235)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:5994)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:6047)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:6013)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:6021)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:5994)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:6047)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:6013)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:6211)
  at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent (ViewRootImpl.java:6391)
  at android.view.inputmethod.InputMethodManager$PendingEvent.run (InputMethodManager.java:3667)
  at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback (InputMethodManager.java:3187)
  at android.view.inputmethod.InputMethodManager.finishedInputEvent (InputMethodManager.java:3178)
  at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished (InputMethodManager.java:3644)
  at android.view.InputEventSender.dispatchInputEventFinished (InputEventSender.java:154)
  at android.os.MessageQueue.nativePollOnce
  at android.os.MessageQueue.next (MessageQueue.java:335)
  at android.os.Looper.loopOnce (Looper.java:185)
  at android.os.Looper.loop (Looper.java:359)
  at android.app.ActivityThread.main (ActivityThread.java:8127)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:942)
```

**Comment by ArnyminerZ** [comment] 2023-09-17 12:19
I'm trying everything that comes to my mind to reproduce this, with no success. It's clear from the error that it's thrown by pressing back after a certificate decision, which sends a second result, causing the error.

I've tried tapping reject and back as quick as possible, and it's not feasible that this is the issue. The other thing that I can think of is that the activity is not getting closed for some reason after accepting the certificate, and the user tries to tap back, which gives a second answer. However, I'm not able to force this behavior by any means.

**Comment by ArnyminerZ** [comment] 2023-09-17 12:26
I've only found it crashing on Android 13, so maybe something to take into consideration...

**Comment by ArnyminerZ** [comment] 2023-09-17 12:30
Maybe replacing the iterator call

https://github.com/bitfireAT/cert4android/blob/8b89eb434489adad0ee0c37e8f5c233de243b7d9/lib/src/main/java/at/bitfire/cert4android/UserDecisionRegistry.kt#L110-L116

with something like?
```kotlin
synchronized(pendingDecisions) {
    pendingDecisions[cert]?.removeAll {
        it.resume(trusted)
        true
    }
}
```

**Comment by ArnyminerZ** [comment] 2023-09-17 12:41
Tried things:
- Quickly tapping multiple options at the same time (eg back and reject, or reject and accept)
- Dismiss notification with decision activity open (activity just closes automatically)

**Comment by ArnyminerZ** [comment] 2023-09-19 07:50
I think this might be related to timeout. In fact, I think it doesn't even work at all. My thoughts are that timeout is giving an answer to the request, but not closing the activity, so whenever you press back, deny or whatever, you are giving an extra answer, which causes the error. I haven't been able to reproduce it yet, though

**Comment by rfc2822** [comment] 2023-09-21 08:12
> I think this might be related to timeout. In fact, I think it doesn't even work at all. My thoughts are that timeout is giving an answer to the request, but not closing the activity, so whenever you press back, deny or whatever, you are giving an extra answer, which causes the error. I haven't been able to reproduce it yet, though.

That's by intention (see #30), however accepting/denying shouldn't give an extra answer. I didn't see where this could happen by now…

**Comment by rfc2822** [comment] 2023-09-21 08:35
> Also no clue why it's only happening on Android 13.

This code is only executing in Android 13 (because the notification permission only exists since Android 13) *and* it contains a `cont.resume()`… quite suspicious:

https://github.com/bitfireAT/cert4android/blob/8b89eb434489adad0ee0c37e8f5c233de243b7d9/lib/src/main/java/at/bitfire/cert4android/UserDecisionRegistry.kt#L90-L95

**Comment by rfc2822** [comment] 2023-09-21 09:42
Found out how to reproduce it 😃

1. Open cert4android demo in Android 13. Make sure that notification permissions are **not** set.
2. Uncheck _App in foreground_
3. Access URL with self-signed certificate. The code cited above sends `cont.resume(false)` and the request fails. However, the request is still in `pendingDecisions`.
4. Check _App in foreground_.
5. Access URL with self-signed certificate again. The activity opens. Accept the certificate.
6. The app crashes with `java.lang.IllegalStateException: Already resumed, but proposed with update false` because all `pendingDecisions` are continued (including the one that has already been continued because the app was in background).

**Closed** 2023-09-21 16:09 UTC
Labels: bug
